### ISSUE TITLE
GC issue: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference

### ISSUE THREAD

**Issue by deindesignpl** [AppLozic/Applozic-NativeScript-Chat-Plugin#30]
Hello,

It happens when we try to invoke isLoggedIn method. We get the error:

`java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference{ nativeException:    { constructor:       { [Function]        extend: [Function],        null: [Circular],        class: { constructor: [Object] } } }, `

It must be something with GC on Android. It also happens only on Android. Only clearing app data helps in that case. Seems it happens when we try to getInstance on com.applozic.mobicomkit.api.account.user.MobiComUserPreference in applozic for android. It's just stuck and this error appears.

**Comment by Sunilkumarr** [comment]
You can use the NS6 version 1.7.0 and uninstall the app from the device and install it.

**Comment by deindesignpl** [comment]
We're currently in process of migration to 2.1.0/2.2.0. I will confirm whether issue persists afterwards.

**Comment by MattCCC** [comment]
Hello @Sunilkumarr , I confirm issue persists on 2.1.0. Basically the same thing when trying to invoke the isLoggedIn method.

**Comment by adel12790** [comment]
Hi, I'm working on v2.2.0 and I had this error while building.

`Execution failed for task ':app:mergeDebugResources'.
Android resource compilation failed
/Users/mohamedadel/.gradle/caches/transforms-2/files-2.1/0f279d52f241ddc1c70630baab066dcc/jetified-TNSGauge-release/res/values/values.xml:29:5-40:25: AAPT: error: duplicate value for resource 'attr/circleRadius' with config ''.
    
/Users/mohamedadel/.gradle/caches/transforms-2/files-2.1/0f279d52f241ddc1c70630baab066dcc/jetified-TNSGauge-release/res/values/values.xml:29:5-40:25: AAPT: error: resource previously defined here.
    
/Users/mohamedadel/Documents/1.Work/2.Projects/Chiliz/2.Projects/frontend-monorepo/com.socios/platforms/android/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml: AAPT: error: file failed to compile.`

I think this might be colliding with the package `nativescript-ui-gauge@7.0.2` that I'm currently using into my project.

Is there a way to solve that?

**Comment by Sunilkumarr** [comment]
@adel12790 I see that issue is from nativescript-ui-feedback https://github.com/ProgressNS/nativescript-ui-feedback/issues/1057

As they are using the same res  `attr/circleRadius` name   which is used in the official google android library  
Either they need to change the name of their resource in their own library so that it wont clash with the official android library or you cloud use another library which is mentioned in the above issue.

**Comment by Sunilkumarr** [comment]
@MattCCC You will have to use 2.2.0 the Nullpointer is fixed in this.

**Comment by Sunilkumarr** [comment]
@adel12790 As gauge library is as defined same values in their own library `attr/circleRadius`  and also android latest of version value constraint layout as same `attr/circleRadius` and gauge library needs to change their values so that it won't clash with the android latest versions.

As we updated our android constraint layout to the latest version in 2.2.0 before it was a too old version constraint layout in 2.1.0

**Comment by adel12790** [comment]
Thanks for the explanation @Sunilkumarr.
